import './globals.css'
import { Inter } from 'next/font/google'
import { TheHeader } from '@/components/header/TheHeader'
import { TheFooter } from '@/components/footer/TheFooter'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Next One',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TheHeader />
        <main>
          {children}
        </main>
        <TheFooter />
      </body>
    </html>
  )
}
